# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Hatena-Exist
version:      0.02
version_from: lib/WebService/Hatena/Exist.pm
installdirs:  site
requires:
    Class::ErrorHandler:           0
    Readonly:                      0
    Test::More:                    0.47
    URI::Fetch::SimpleCache:       0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
